apiVersion: v1
kind: Service
metadata:
  name: {{ include "topic-freshness-exporter.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "topic-freshness-exporter.name" . }}
  ports:
  - name: http
    port: 8000
    targetPort: 8000
